### ISSUE TITLE
undefined method `register_middleware'

### ISSUE THREAD

**Issue by dblsystems** [lgromanowski/letsencrypt-plugin#18]
Once I add the gem to my gemfile i'm getting the following error from Faraday when trying to run the rails server, run generators/etc. Stack trace below but i'm using Ruby 2.2.3 and Rails 4.2.5.

```xxxx@machine:~/dev/2013/2012_02_boab/proj_2013 (610-update-ssl-cert)\ॐ rails s
/Users/xxxx/.rvm/gems/ruby-2.2.3@proj_2015/gems/faraday-0.9.2/lib/faraday.rb:99:in `method_missing': undefined method `register_middleware' for #<Faraday::Connection:0x007f9deb6ae178> (NoMethodError)
  from /Users/xxxx/.rvm/gems/ruby-2.2.3@proj_2015/gems/balanced-0.7.4/lib/balanced/client.rb:41:in `build_conn'
  from /Users/xxxx/.rvm/gems/ruby-2.2.3@proj_2015/gems/balanced-0.7.4/lib/balanced/client.rb:30:in `initialize'
  from /Users/xxxx/.rvm/gems/ruby-2.2.3@proj_2015/gems/balanced-0.7.4/lib/balanced.rb:29:in `new'
  from /Users/xxxx/.rvm/gems/ruby-2.2.3@proj_2015/gems/balanced-0.7.4/lib/balanced.rb:29:in `configure'
  from /Users/xxxx/.rvm/gems/ruby-2.2.3@proj_2015/gems/balanced-0.7.4/lib/balanced.rb:86:in `<module:Balanced>'
  from /Users/xxxx/.rvm/gems/ruby-2.2.3@proj_2015/gems/balanced-0.7.4/lib/balanced.rb:11:in `<top (required)>'
  from /Users/xxxx/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
  from /Users/xxxx/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
  from /Users/xxxx/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
  from /Users/xxxx/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'
  from /Users/xxxx/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
  from /Users/xxxx/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
  from /Users/xxxx/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
  from /Users/xxxx/Dropbox/xxxx/DBL/dev/2013/2012_02_boab/proj_2013/config/application.rb:11:in `<top (required)>'
  from /Users/xxxx/.rvm/gems/ruby-2.2.3@proj_2015/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:78:in `require'
  from /Users/xxxx/.rvm/gems/ruby-2.2.3@proj_2015/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:78:in `block in server'
  from /Users/xxxx/.rvm/gems/ruby-2.2.3@proj_2015/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:75:in `tap'
  from /Users/xxxx/.rvm/gems/ruby-2.2.3@proj_2015/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:75:in `server'
  from /Users/xxxx/.rvm/gems/ruby-2.2.3@proj_2015/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  from /Users/xxxx/.rvm/gems/ruby-2.2.3@proj_2015/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
  from bin/rails:8:in `require'
  from bin/rails:8:in `<main>'
```

**Comment by lgromanowski** [comment]
Hi,
faraday is used by acme-client gem, could you please post your Gemfile and Gemfile.lock? Also could you check if ```bundle update``` will help?

**Comment by dblsystems** [comment]
tried running bundle update as well and while it runs we still get the same issue.


```
source 'https://rubygems.org'
ruby "2.2.3"

gem 'rails', '~> 4.2.4'

gem 'unicorn', :group => :production
gem 'thin', :group => :development
gem 'sass-rails' #, '4.0.2' 
gem "sprockets", "2.11.0" #backport until they update for sass-rails
gem 'coffee-rails' #, '~> 4.1.0' #, '~> 3.2.1'
gem 'uglifier' #, '>= 1.3.0' #, '>= 1.0.3'
gem 'foundation-icons-sass-rails'

gem 'RedCloth'
gem 'BlueCloth'
gem 'acts-as-taggable-on'
gem 'httparty'
gem 'jquery-rails'
gem "pg"
gem "haml-rails" #, ">= 0.3.5", :group => :development
gem "hpricot", ">= 0.8.6", :group => :development
gem "ruby_parser", ">= 3.1.1", :group => :development
gem "rspec-rails" #, ">= 2.11.4", :group => [:development, :test]
#gem "guard-rspec", :group => [:development, :test]
gem "capybara", ">= 2.0.1", :group => :test
gem "database_cleaner", ">= 0.9.1", :group => :test
gem "email_spec", ">= 1.4.0", :group => :test
gem 'faker', :group => :test
gem "factory_girl_rails", ">= 4.1.0", :group => [:development, :test]
gem "bootstrap-sass", "~> 2.3.2.2"
gem 'mandrill-api'
gem "omniauth" #, ">= 1.1.1"
gem "omniauth-facebook"
gem "omniauth-twitter"
gem "omniauth-google-oauth2"
gem "omniauth-identity"

gem 'bcrypt' #, '~> 3.0.0' commented out for RoR 4.0.1.rc3
gem "cancan", ">= 1.6.8"
gem "rolify", ">= 3.2.0"
gem "simple_form", ">= 2.0.4"
gem 'country_select'
gem "quiet_assets", ">= 1.0.1", :group => :development
gem "figaro", ">= 0.5.0"
gem 'byebug', :group => :development
gem 'web-console', '~> 2.0', :group => :development

gem "better_errors", ">= 0.7.2", :group => :development
gem "binding_of_caller", ">= 0.7.1", :group => :development
gem "jquery-ui-rails"
gem 'filepicker-rails'
gem "acts_as_opengraph", "~> 0.0.5"
gem "rmagick", require: false
gem "aws-sdk"
gem 'carrierwave'
gem "mini_magick"
gem "fog" #, "~> 1.3.1"
gem "best_in_place", :git => 'https://github.com/aaronchi/best_in_place.git'
gem 'pg_search'
gem 'will_paginate', :git => 'https://github.com/nazgum/will_paginate.git' #until rails 4.1 will_paginate fixed
gem 'ancestry'
gem "newrelic_rpm"
gem 'phony_rails'
gem "desk"
gem 'sentry-raven', :group => :production
gem 'dalli'
gem 'memcachier'
gem 'rails_12factor', group: [:production]
gem 'protected_attributes' #added for RoR 4.0.0
gem 'rails-observers' #added for RoR 4.0.0
gem 'activerecord-deprecated_finders' #added for RoR 4.0.0
gem "linguistics", "~> 2.0.2"

gem 'rack-mini-profiler', :group => :development

gem 'twilio-ruby'

gem 'ruby-trello'
gem 'aasm' #state machine for order process
gem "balanced", "~> 0.7.4"
gem "medium-editor-rails", "~> 0.3.0"
gem "letter_opener", :group => :development

gem 'thread_safe' #, '0.2.0' #added for heroku fail - http://stackoverflow.com/questions/22510461/could-not-find-thread-safe-0-3-0-in-any-of-the-sources
gem 'delayed_job_active_record'
gem 'pry', :group => :development
gem 'pry-remote', :group => :development
gem 'jquery-simplecolorpicker-rails'
gem 'gibbon'
gem 'stripe', :git => 'https://github.com/stripe/stripe-ruby'

gem 'responders'
gem 'react-rails', '~> 1.0'
gem 'xero_gateway'
gem 'certified'

#lets encrypt
gem 'letsencrypt_plugin'

```

Gemfile.lock

```
GIT
  remote: https://github.com/aaronchi/best_in_place.git
  revision: 1152e2256afd485e66602833fd99d09d60994841
  specs:
    best_in_place (2.1.0)
      jquery-rails
      rails (>= 3.1)

GIT
  remote: https://github.com/nazgum/will_paginate.git
  revision: 887d615971e76c01d19e2e274856129acf5b9ec3
  specs:
    will_paginate (3.0.4)

GIT
  remote: https://github.com/stripe/stripe-ruby
  revision: 0c14e6ec1f5a4598c9d29f3945d110570e6413cf
  specs:
    stripe (1.32.1)
      json (~> 1.8.1)
      rest-client (~> 1.4)

GEM
  remote: https://rubygems.org/
  specs:
    BlueCloth (1.0.1)
    CFPropertyList (2.3.2)
    RedCloth (4.2.9)
    aasm (4.7.0)
    acme-client (0.2.4)
      faraday (~> 0.9, >= 0.9.1)
      json-jwt (~> 1.2, >= 1.2.3)
    actionmailer (4.2.5)
      actionpack (= 4.2.5)
      actionview (= 4.2.5)
      activejob (= 4.2.5)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.5)
      actionview (= 4.2.5)
      activesupport (= 4.2.5)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (4.2.5)
      activesupport (= 4.2.5)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    activejob (4.2.5)
      activesupport (= 4.2.5)
      globalid (>= 0.3.0)
    activemodel (4.2.5)
      activesupport (= 4.2.5)
      builder (~> 3.1)
    activerecord (4.2.5)
      activemodel (= 4.2.5)
      activesupport (= 4.2.5)
      arel (~> 6.0)
    activerecord-deprecated_finders (1.0.4)
    activesupport (4.2.5)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    acts-as-taggable-on (3.5.0)
      activerecord (>= 3.2, < 5)
    acts_as_opengraph (0.0.5)
    addressable (2.4.0)
    ancestry (2.1.0)
      activerecord (>= 3.0.0)
    arel (6.0.3)
    aws-sdk (2.2.11)
      aws-sdk-resources (= 2.2.11)
    aws-sdk-core (2.2.11)
      jmespath (~> 1.0)
    aws-sdk-resources (2.2.11)
      aws-sdk-core (= 2.2.11)
    babel-source (5.8.34)
    babel-transpiler (0.7.0)
      babel-source (>= 4.0, < 6)
      execjs (~> 2.0)
    balanced (0.7.4)
      faraday (>= 0.8.6)
      faraday_middleware (~> 0.9.0)
    bcrypt (3.1.10)
    bcrypt-ruby (3.1.5)
      bcrypt (>= 3.1.3)
    better_errors (2.1.1)
      coderay (>= 1.0.0)
      erubis (>= 2.6.6)
      rack (>= 0.9.0)
    bindata (2.1.0)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    bootstrap-sass (2.3.2.2)
      sass (~> 3.2)
    builder (3.2.2)
    byebug (8.2.1)
    cancan (1.6.10)
    capybara (2.6.0)
      addressable
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    carrierwave (0.10.0)
      activemodel (>= 3.2.0)
      activesupport (>= 3.2.0)
      json (>= 1.7)
      mime-types (>= 1.16)
    certified (1.0.0)
    coderay (1.1.0)
    coffee-rails (4.1.1)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.1.x)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.10.0)
    connection_pool (2.2.0)
    countries (1.2.2)
      currencies (~> 0.4.2)
      i18n_data (~> 0.7.0)
    country_select (2.5.1)
      countries (~> 1.2.0)
      sort_alphabetical (~> 1.0)
    currencies (0.4.2)
    daemons (1.2.3)
    dalli (2.7.5)
    database_cleaner (1.5.1)
    debug_inspector (0.0.2)
    delayed_job (4.1.1)
      activesupport (>= 3.0, < 5.0)
    delayed_job_active_record (4.1.0)
      activerecord (>= 3.0, < 5)
      delayed_job (>= 3.0, < 5)
    desk (1.0.8)
      faraday (~> 0.9.0)
      faraday_middleware (~> 0.9.0)
      hashie (= 3.4.1)
      multi_json (~> 1.6)
      multi_xml (~> 0.5)
      pony (~> 1.1)
      simple_oauth (~> 0.2.0)
    diff-lcs (1.2.5)
    domain_name (0.5.25)
      unf (>= 0.0.5, < 1.0.0)
    email_spec (2.0.0)
      htmlentities (~> 4.3.3)
      launchy (~> 2.1)
      mail (~> 2.6.3)
    erubis (2.7.0)
    eventmachine (1.0.9.1)
    excon (0.45.4)
    execjs (2.6.0)
    factory_girl (4.5.0)
      activesupport (>= 3.0.0)
    factory_girl_rails (4.5.0)
      factory_girl (~> 4.5.0)
      railties (>= 3.0.0)
    faker (1.6.1)
      i18n (~> 0.5)
    faraday (0.9.2)
      multipart-post (>= 1.2, < 3)
    faraday_middleware (0.9.2)
      faraday (>= 0.7.4, < 0.10)
    figaro (1.1.1)
      thor (~> 0.14)
    filepicker-rails (2.1.0)
      rails (>= 3.2)
    fission (0.5.0)
      CFPropertyList (~> 2.2)
    fog (1.37.0)
      fog-aliyun (>= 0.1.0)
      fog-atmos
      fog-aws (>= 0.6.0)
      fog-brightbox (~> 0.4)
      fog-core (~> 1.32)
      fog-dynect (~> 0.0.2)
      fog-ecloud (~> 0.1)
      fog-google (<= 0.1.0)
      fog-json
      fog-local
      fog-powerdns (>= 0.1.1)
      fog-profitbricks
      fog-radosgw (>= 0.0.2)
      fog-riakcs
      fog-sakuracloud (>= 0.0.4)
      fog-serverlove
      fog-softlayer
      fog-storm_on_demand
      fog-terremark
      fog-vmfusion
      fog-voxel
      fog-vsphere (>= 0.4.0)
      fog-xenserver
      fog-xml (~> 0.1.1)
      ipaddress (~> 0.5)
    fog-aliyun (0.1.0)
      fog-core (~> 1.27)
      fog-json (~> 1.0)
      ipaddress (~> 0.8)
      xml-simple (~> 1.1)
    fog-atmos (0.1.0)
      fog-core
      fog-xml
    fog-aws (0.8.1)
      fog-core (~> 1.27)
      fog-json (~> 1.0)
      fog-xml (~> 0.1)
      ipaddress (~> 0.8)
    fog-brightbox (0.10.1)
      fog-core (~> 1.22)
      fog-json
      inflecto (~> 0.0.2)
    fog-core (1.35.0)
      builder
      excon (~> 0.45)
      formatador (~> 0.2)
    fog-dynect (0.0.2)
      fog-core
      fog-json
      fog-xml
    fog-ecloud (0.3.0)
      fog-core
      fog-xml
    fog-google (0.1.0)
      fog-core
      fog-json
      fog-xml
    fog-json (1.0.2)
      fog-core (~> 1.0)
      multi_json (~> 1.10)
    fog-local (0.2.1)
      fog-core (~> 1.27)
    fog-powerdns (0.1.1)
      fog-core (~> 1.27)
      fog-json (~> 1.0)
      fog-xml (~> 0.1)
    fog-profitbricks (0.0.5)
      fog-core
      fog-xml
      nokogiri
    fog-radosgw (0.0.5)
      fog-core (>= 1.21.0)
      fog-json
      fog-xml (>= 0.0.1)
    fog-riakcs (0.1.0)
      fog-core
      fog-json
      fog-xml
    fog-sakuracloud (1.7.5)
      fog-core
      fog-json
    fog-serverlove (0.1.2)
      fog-core
      fog-json
    fog-softlayer (1.0.3)
      fog-core
      fog-json
    fog-storm_on_demand (0.1.1)
      fog-core
      fog-json
    fog-terremark (0.1.0)
      fog-core
      fog-xml
    fog-vmfusion (0.1.0)
      fission
      fog-core
    fog-voxel (0.1.0)
      fog-core
      fog-xml
    fog-vsphere (0.5.0)
      fog-core
      rbvmomi (~> 1.8)
    fog-xenserver (0.2.3)
      fog-core
      fog-xml
    fog-xml (0.1.2)
      fog-core
      nokogiri (~> 1.5, >= 1.5.11)
    formatador (0.2.5)
    foundation-icons-sass-rails (3.0.0)
      railties (>= 3.1.1)
      sass-rails (>= 3.1.1)
    gibbon (2.2.1)
      faraday (>= 0.9.1)
      multi_json (>= 1.11.0)
    globalid (0.3.6)
      activesupport (>= 4.1.0)
    haml (4.0.7)
      tilt
    haml-rails (0.9.0)
      actionpack (>= 4.0.1)
      activesupport (>= 4.0.1)
      haml (>= 4.0.6, < 5.0)
      html2haml (>= 1.0.1)
      railties (>= 4.0.1)
    hashie (3.4.1)
    hike (1.2.3)
    hpricot (0.8.6)
    html2haml (2.0.0)
      erubis (~> 2.7.0)
      haml (~> 4.0.0)
      nokogiri (~> 1.6.0)
      ruby_parser (~> 3.5)
    htmlentities (4.3.4)
    http-cookie (1.0.2)
      domain_name (~> 0.5)
    httparty (0.13.7)
      json (~> 1.8)
      multi_xml (>= 0.5.2)
    i18n (0.7.0)
    i18n_data (0.7.0)
    inflecto (0.0.2)
    ipaddress (0.8.2)
    jmespath (1.1.3)
    jquery-rails (4.1.0)
      rails-dom-testing (~> 1.0)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    jquery-simplecolorpicker-rails (0.5.0)
      railties (>= 3.1.0)
    jquery-ui-rails (5.0.5)
      railties (>= 3.2.16)
    json (1.8.3)
    json-jwt (1.5.1)
      activesupport
      bindata
      multi_json (>= 1.3)
      securecompare
      url_safe_base64
    jwt (1.5.2)
    kgio (2.10.0)
    launchy (2.4.3)
      addressable (~> 2.3)
    letsencrypt_plugin (0.0.6)
      acme-client (~> 0.2.4)
      rails (~> 4.2.5)
    letter_opener (1.4.1)
      launchy (~> 2.2)
    linguistics (2.0.4)
      loggability (~> 0.11)
    loggability (0.11.0)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    mail (2.6.3)
      mime-types (>= 1.16, < 3)
    mandrill-api (1.0.53)
      excon (>= 0.16.0, < 1.0)
      json (>= 1.7.7, < 2.0)
    medium-editor-rails (0.3.0)
    memcachier (0.0.2)
    method_source (0.8.2)
    mime-types (2.99)
    mini_magick (4.3.6)
    mini_portile2 (2.0.0)
    minitest (5.8.3)
    multi_json (1.11.2)
    multi_xml (0.5.5)
    multipart-post (2.0.0)
    netrc (0.11.0)
    newrelic_rpm (3.14.1.311)
    nokogiri (1.6.7.1)
      mini_portile2 (~> 2.0.0.rc2)
    oauth (0.4.7)
    oauth2 (1.0.0)
      faraday (>= 0.8, < 0.10)
      jwt (~> 1.0)
      multi_json (~> 1.3)
      multi_xml (~> 0.5)
      rack (~> 1.2)
    omniauth (1.3.1)
      hashie (>= 1.2, < 4)
      rack (>= 1.0, < 3)
    omniauth-facebook (3.0.0)
      omniauth-oauth2 (~> 1.2)
    omniauth-google-oauth2 (0.3.0)
      addressable (~> 2.3)
      jwt (~> 1.0)
      multi_json (~> 1.3)
      omniauth (>= 1.1.1)
      omniauth-oauth2 (>= 1.3.1)
    omniauth-identity (1.1.1)
      bcrypt-ruby (~> 3.0)
      omniauth (~> 1.0)
    omniauth-oauth (1.1.0)
      oauth
      omniauth (~> 1.0)
    omniauth-oauth2 (1.4.0)
      oauth2 (~> 1.0)
      omniauth (~> 1.2)
    omniauth-twitter (1.2.1)
      json (~> 1.3)
      omniauth-oauth (~> 1.1)
    pg (0.18.4)
    pg_search (1.0.5)
      activerecord (>= 3.1)
      activesupport (>= 3.1)
      arel
    phony (2.15.14)
    phony_rails (0.12.11)
      activesupport (>= 3.0)
      phony (~> 2.12)
    pony (1.11)
      mail (>= 2.0)
    protected_attributes (1.1.3)
      activemodel (>= 4.0.1, < 5.0)
    pry (0.10.3)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    pry-remote (0.1.8)
      pry (~> 0.9)
      slop (~> 3.0)
    quiet_assets (1.1.0)
      railties (>= 3.1, < 5.0)
    rack (1.6.4)
    rack-mini-profiler (0.9.8)
      rack (>= 1.1.3)
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.2.5)
      actionmailer (= 4.2.5)
      actionpack (= 4.2.5)
      actionview (= 4.2.5)
      activejob (= 4.2.5)
      activemodel (= 4.2.5)
      activerecord (= 4.2.5)
      activesupport (= 4.2.5)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.5)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.7)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6.0)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.2)
      loofah (~> 2.0)
    rails-observers (0.1.2)
      activemodel (~> 4.0)
    rails_12factor (0.0.3)
      rails_serve_static_assets
      rails_stdout_logging
    rails_serve_static_assets (0.0.4)
    rails_stdout_logging (0.0.4)
    railties (4.2.5)
      actionpack (= 4.2.5)
      activesupport (= 4.2.5)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    raindrops (0.15.0)
    rake (10.5.0)
    rbvmomi (1.8.2)
      builder
      nokogiri (>= 1.4.1)
      trollop
    react-rails (1.5.0)
      babel-transpiler (>= 0.7.0)
      coffee-script-source (~> 1.8)
      connection_pool
      execjs
      rails (>= 3.2)
      tilt
    responders (2.1.1)
      railties (>= 4.2.0, < 5.1)
    rest-client (1.8.0)
      http-cookie (>= 1.0.2, < 2.0)
      mime-types (>= 1.16, < 3.0)
      netrc (~> 0.7)
    rmagick (2.15.4)
    rolify (5.0.0)
    rspec-core (3.4.1)
      rspec-support (~> 3.4.0)
    rspec-expectations (3.4.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.4.0)
    rspec-mocks (3.4.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.4.0)
    rspec-rails (3.4.0)
      actionpack (>= 3.0, < 4.3)
      activesupport (>= 3.0, < 4.3)
      railties (>= 3.0, < 4.3)
      rspec-core (~> 3.4.0)
      rspec-expectations (~> 3.4.0)
      rspec-mocks (~> 3.4.0)
      rspec-support (~> 3.4.0)
    rspec-support (3.4.1)
    ruby-trello (1.4.1)
      activemodel (>= 3.2.0)
      addressable (~> 2.3)
      json
      oauth (~> 0.4.5)
      rest-client (~> 1.8.0)
    ruby_parser (3.7.2)
      sexp_processor (~> 4.1)
    sass (3.4.21)
    sass-rails (5.0.4)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    securecompare (1.0.0)
    sentry-raven (0.15.3)
      faraday (>= 0.7.6)
    sexp_processor (4.6.0)
    simple_form (3.2.1)
      actionpack (> 4, < 5.1)
      activemodel (> 4, < 5.1)
    simple_oauth (0.2.0)
    slop (3.6.0)
    sort_alphabetical (1.0.2)
      unicode_utils (>= 1.2.2)
    sprockets (2.11.0)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sprockets-rails (2.3.3)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (>= 2.8, < 4.0)
    thin (1.6.4)
      daemons (~> 1.0, >= 1.0.9)
      eventmachine (~> 1.0, >= 1.0.4)
      rack (~> 1.0)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (1.4.1)
    trollop (2.1.2)
    twilio-ruby (4.9.0)
      builder (>= 2.1.2)
      jwt (~> 1.0)
      multi_json (>= 1.3.0)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.7.2)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.1)
    unicode_utils (1.4.0)
    unicorn (5.0.1)
      kgio (~> 2.6)
      rack
      raindrops (~> 0.7)
    url_safe_base64 (0.2.2)
    web-console (2.2.1)
      activemodel (>= 4.0)
      binding_of_caller (>= 0.7.2)
      railties (>= 4.0)
      sprockets-rails (>= 2.0, < 4.0)
    xero_gateway (2.1.0)
      activesupport
      builder (>= 2.1.2)
      oauth (>= 0.3.6)
    xml-simple (1.1.5)
    xpath (2.0.0)
      nokogiri (~> 1.3)

PLATFORMS
  ruby

DEPENDENCIES
  BlueCloth
  RedCloth
  aasm
  activerecord-deprecated_finders
  acts-as-taggable-on
  acts_as_opengraph (~> 0.0.5)
  ancestry
  aws-sdk
  balanced (~> 0.7.4)
  bcrypt
  best_in_place!
  better_errors (>= 0.7.2)
  binding_of_caller (>= 0.7.1)
  bootstrap-sass (~> 2.3.2.2)
  byebug
  cancan (>= 1.6.8)
  capybara (>= 2.0.1)
  carrierwave
  certified
  coffee-rails
  country_select
  dalli
  database_cleaner (>= 0.9.1)
  delayed_job_active_record
  desk
  email_spec (>= 1.4.0)
  factory_girl_rails (>= 4.1.0)
  faker
  figaro (>= 0.5.0)
  filepicker-rails
  fog
  foundation-icons-sass-rails
  gibbon
  haml-rails
  hpricot (>= 0.8.6)
  httparty
  jquery-rails
  jquery-simplecolorpicker-rails
  jquery-ui-rails
  letsencrypt_plugin
  letter_opener
  linguistics (~> 2.0.2)
  mandrill-api
  medium-editor-rails (~> 0.3.0)
  memcachier
  mini_magick
  newrelic_rpm
  omniauth
  omniauth-facebook
  omniauth-google-oauth2
  omniauth-identity
  omniauth-twitter
  pg
  pg_search
  phony_rails
  protected_attributes
  pry
  pry-remote
  quiet_assets (>= 1.0.1)
  rack-mini-profiler
  rails (~> 4.2.4)
  rails-observers
  rails_12factor
  react-rails (~> 1.0)
  responders
  rmagick
  rolify (>= 3.2.0)
  rspec-rails
  ruby-trello
  ruby_parser (>= 3.1.1)
  sass-rails
  sentry-raven
  simple_form (>= 2.0.4)
  sprockets (= 2.11.0)
  stripe!
  thin
  thread_safe
  twilio-ruby
  uglifier
  unicorn
  web-console (~> 2.0)
  will_paginate!
  xero_gateway

BUNDLED WITH
   1.10.6
```

**Comment by lgromanowski** [comment]
Ok, there is a conflict between ```balanced```gem and ```acme-client``` - 1st one requires faraday >= v0.8.6; <= v0.9.0, faraday_middleware ~> v0.9.0, while 2nd one requires faraday v0.9.1, ~> 0.9.

Balanced gem is quite old (latest release was in 19th Dec 2014), and there is a bug report related to faraday: https://github.com/balanced/balanced-ruby/issues/173

 Would it be possible to use some kind of replacement for this gem, and try again with letsencrypt-plugin?

**Comment by dblsystems** [comment]
looks like that solved the problem. balanced payments shut down a while back and we migrated over to stripe but the gem was still being loaded in the gemfile...
