### ISSUE TITLE
uninitialized constant OpenSSL::PKey::EC

### ISSUE THREAD

**Issue by calebsmithdeveloper2012** [lgromanowski/letsencrypt-plugin#29]
On Max OSX using jruby 9.0.5.0 I get the error "uninitialized constant OpenSSL::PKey::EC"

**Comment by lgromanowski** [comment]
Hi,
could you please post ruby trace?

**Comment by p0indexter** [comment]
Trace:

`200-168-100-8:employment calebmitchellsmith$ rake letsencrypt_plugin --trace
NOTE: ActiveRecord 4.2 with adapter: mssql is not (yet) fully supported by AR-JDBC, please consider helping us out.
rake aborted!
NameError: uninitialized constant OpenSSL::PKey::EC
/Users/calebmitchellsmith/.rvm/gems/jruby-9.0.5.0@emp2/gems/json-jwt-1.5.2/lib/json/jwk/jwkizable.rb:69:in `<top>'
/Users/calebmitchellsmith/.rvm/gems/jruby-9.0.5.0@emp2/gems/json-jwt-1.5.2/lib/json/jwt.rb:1:in `<top>'
/Users/calebmitchellsmith/.rvm/gems/jruby-9.0.5.0@emp2/gems/json-jwt-1.5.2/lib/json/jwt.rb:102:in `<top>'
/Users/calebmitchellsmith/.rvm/gems/jruby-9.0.5.0@emp2/gems/acme-client-0.3.0/lib/acme-client.rb:1:in `<top>'
/Users/calebmitchellsmith/.rvm/gems/jruby-9.0.5.0@emp2/gems/acme-client-0.3.0/lib/acme-client.rb:5:in `<top>'
/Users/calebmitchellsmith/.rvm/gems/jruby-9.0.5.0@emp2/gems/acme-client-0.3.0/lib/acme/client.rb:1:in `require'
/Users/calebmitchellsmith/.rvm/gems/jruby-9.0.5.0@emp2/gems/acme-client-0.3.0/lib/acme/client.rb:1:in `block in (root)'
/Users/calebmitchellsmith/.rvm/gems/jruby-9.0.5.0@emp2/gems/acme-client-0.3.0/lib/acme/client.rb:1:in `each'
/Users/calebmitchellsmith/.rvm/gems/jruby-9.0.5.0@emp2/gems/acme-client-0.3.0/lib/acme/client.rb:1:in `block in (root)'
/Users/calebmitchellsmith/.rvm/gems/jruby-9.0.5.0@emp2/bundler/gems/letsencrypt-plugin-e75ceed41c55/lib/letsencrypt_plugin.rb:1:in `each'
/Users/calebmitchellsmith/.rvm/gems/jruby-9.0.5.0@emp2/bundler/gems/letsencrypt-plugin-e75ceed41c55/lib/letsencrypt_plugin.rb:1:in `(root)'
/Users/calebmitchellsmith/.rvm/gems/jruby-9.0.5.0@emp2/bundler/gems/letsencrypt-plugin-e75ceed41c55/lib/letsencrypt_plugin.rb:7:in `(root)'
/Users/calebmitchellsmith/.rvm/gems/jruby-9.0.5.0@emp2/gems/bundler-1.9.9/lib/bundler/runtime.rb:1:in `<top>'
/Users/calebmitchellsmith/.rvm/rubies/jruby-9.0.5.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/calebmitchellsmith/.rvm/rubies/jruby-9.0.5.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/calebmitchellsmith/.rvm/gems/jruby-9.0.5.0@emp2/gems/bundler-1.9.9/lib/bundler/runtime.rb:76:in `<top>'
/Users/calebmitchellsmith/.rvm/gems/jruby-9.0.5.0@emp2/gems/bundler-1.9.9/lib/bundler/runtime.rb:72:in `load'
/Users/calebmitchellsmith/.rvm/gems/jruby-9.0.5.0@emp2/gems/bundler-1.9.9/lib/bundler/runtime.rb:72:in `require'
/Users/calebmitchellsmith/.rvm/gems/jruby-9.0.5.0@emp2/gems/bundler-1.9.9/lib/bundler/runtime.rb:61:in `require'
/Users/calebmitchellsmith/.rvm/gems/jruby-9.0.5.0@emp2/gems/bundler-1.9.9/lib/bundler.rb:134:in `block in require'
/Users/calebmitchellsmith/Dropbox/Programing/Ruby/EMI/FTN/employment/config/application.rb:25:in `(root)'
/Users/calebmitchellsmith/Dropbox/Programing/Ruby/EMI/FTN/employment/Rakefile:1:in `(root)'
/Users/calebmitchellsmith/Dropbox/Programing/Ruby/EMI/FTN/employment/Rakefile:4:in `block in (root)'
/Users/calebmitchellsmith/.rvm/gems/jruby-9.0.5.0@global/gems/rake-10.5.0/lib/rake/rake_module.rb:1:in `(root)'
/Users/calebmitchellsmith/.rvm/gems/jruby-9.0.5.0@global/gems/rake-10.5.0/lib/rake/rake_module.rb:28:in `load_rakefile'
/Users/calebmitchellsmith/.rvm/gems/jruby-9.0.5.0@global/gems/rake-10.5.0/lib/rake/application.rb:690:in `<top>'
/Users/calebmitchellsmith/.rvm/gems/jruby-9.0.5.0@global/bin/rake:23:in `load'
/Users/calebmitchellsmith/.rvm/gems/jruby-9.0.5.0@global/bin/rake:23:in `<top>'
`

**Comment by lgromanowski** [comment]
Hi,
it seems to be related to: https://github.com/jruby/jruby/issues/1261 - could you please check on most recent one version of jruby?

**Comment by p0indexter** [comment]
This trace is from the most recent version - 9.0.5.0

**Comment by p0indexter** [comment]
Opps, it looks like this is indeed a jRuby issue, down the thread they state the error resurfaced in jRuby 9K. Im going to try 1.7.13 and work my way up from there, to find which version of jRuby reintroduced the bug.
